version: '2'

services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true'
    environment:
      - ENABLE_IPV6=true
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/srv/nginx/certs:/etc/nginx/certs:ro'
      - '/srv/nginx/vhost.d:/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/srv/nginx/conf.d:/etc/nginx/conf.d'

  nginx-proxy2:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - '/srv/nginx/certs:/etc/nginx/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  mongo:
    image: mongo:latest
    privileged: true
    restart: always
    volumes:
      - '/srv/mongodb:/data/db'

  redis:
    image: redis:latest
    privileged: true
    restart: always

  timemuinonl: 
       image: muino/time-management:latest
       restart: always
       privileged: true
       environment:
         - NODE_ENV=production
         - SERVER_PORT=80
         - JWT_SECRET=jaoipdfjaiojfefj2po3ij4i2je=
         - MONGO_HOST=mongodb://mongo/muinotimeaccounting
         - REDIS_HOST=redis
         - REDIS_PORT=6379
         - VIRTUAL_HOST=time.muino.nl
         - VIRTUAL_PORT=80
         - LETSENCRYPT_HOST=time.muino.nl
         - LETSENCRYPT_EMAIL=admin@muino.nl
         - SMTP_HOST=mail.muino.nl
         - SMTP_PORT=587
         - SMTP_SECURE=false 
         - SMTP_USER=no-reply@muino.nl
         - SMTP_PASS=BIEEEMBLAAT
         #- MONGO_USER=somemongdbuser
         #- MONGO_PWD=jpkoasjggrporeno2345
       depends_on:
         - nginx
         - mongo
         - redis
       volumes:
          - '/srv/muino/avatars:/usr/src/app/dist/muino/assets/img/avatars/' # check if this is the directory you want